### ISSUE TITLE
Store Spotlight/Your Perks menu

### ISSUE THREAD

**Issue by Pugabyte** [ProjectEdenGG/Issues#12]
Two things I have noticed over time regarding the user's knowledge of our store:
- They don't know about a lot of the items in it
- They don't know what they've bought

In-game menus should be built to address both of these problems

**Comment by BearNationSMP** [comment]
**Pugabyte**: Ideas for better advertising the store
Using a donation goal for a server-wide reward
Monthly versions of existing perks for less money

**Comment by BearNationSMP** [comment]
**Pugabyte**: Server-wide boosters

**Comment by FilidDamhsoir** [comment]
Yeah leave the snaller monthly for the ones hardest to test- and highest cost. Prefix, autosort, player vaults?

**Comment by Noahkiq** [comment]
I think the server wide boosters should only last 24 hours or so, but with options to buy several at a time (maybe at a discount?) and either automatically activate them throughout some time frame, activate them all at once to add to the effects (ie buy two 2x boosters for a 3x boost) (also, a limit should probably be added to how many boosters can be stacked at once), or keep them stored in some command for the player to activate at any time.

**Comment by Pugabyte** [comment]
Ideas from meeting form:

- Start with a lower goal
- Conditional advertisements
    - For example: If your inventory gets full, koda will say "Hey there; I see your inventory is getting full. Have you considered buying a Vault to hold your items in a chest you can access anywhere with a command?"
    - Only send this *very* periodically.
    - Probably needs #50 done

**Comment by GriffinCodes** [comment]
Perks menu completed, `/store packages`

Store spotlight will be handled in #50
