### ISSUE TITLE
Murder

### ISSUE THREAD

**Issue by Pugabyte** [ProjectEdenGG/Issues#26]
Though Murder is working and seems to have most bugs ironed out, there are still some things I would like to research and attempt.

- [x] Spectating
    - Instead of teleporting the player to the GL when they die, turn the player invisible, set their collidable state to false, and allow them to fly around the map. See v1 for the original setup for this.
    - [ ] Dead chat
    - [ ] Blindness for 2 seconds on death
- [x] @JustSteveThings suggested having an ActionBar line display what role you are throughout the game. 
   - This can be used to add roleplaying
 
- [x] Better scrap spawning formula
     - Currently it just uses a set number, which is configurable per map by the MGMs. I would like to attempt to add a formula that adjusts the chance for a scrap spawning on each attempt based on...
        - Amount of players in the game
        - Size of map
        - Amount of scrap points
        - Time elapsed in game
        - etc

- [x] Fixing the Minigames side of things
    - There's some currently unfixable problems due to the restrictions of the Minigame plugin, such as...
        - [x] Duplicate messages on match start
        - [x] Disabling death messages
        - [x] Scoreboard

- [ ] ~~@lexikiq would like gun upgrades.~~
  - lexi: probably not a good idea, it's already hard for murderers in the late game with how many players have guns.

- [x] Placing a skull at the location the player died (Armour stands probably, maybe NPCs)

- [x] Scoreboard at the beginning and end of the match? Will probably conflict with Minigames plugin
- [x] Refactoring code
    - It's mostly all in one listener right now, it would be beneficial for future development to clean this up

If you find a bug with an existing murder feature, please make a new issue. This thread is for improvements to the [MVP](https://en.wikipedia.org/wiki/Minimum_viable_product), not maintenance.

**Comment by Noahkiq** [comment]
> Scoreboard at the beginning and end of the match? **Will probably conflict with Minigames plugin**  
There is an option to disable the scoreboard (which is currently setup) though there are times where it shows up anyway (but only shows teams)

**Comment by lexikiq** [comment]
finished the few remaining suggestions, except for dead chat. (spectating already existed, just hadn't been checked off yet)

**Comment by GriffinCodes** [comment]
Gonna call dead chat unnecessary for now and close this issue
