### ISSUE TITLE
Wiki updating

### ISSUE THREAD

**Issue by Pugabyte** [ProjectEdenGG/Issues#29]
Our wiki is generally pretty good at staying up to date, except for staff commands. I need to go through all of my command files and add documentation.

We also need an [Adventure Maps page](https://wiki.bear-nation.net/wiki/Adventure_Maps). I believe @TheCapricious was going to do this

**Comment by BearNationSMP** [comment]
**Filid**: The shop commands are in the mod misc section, but seem to lack the one for removing the owner from a plaza/mall shop... *assuming there is one.*  It deletes the warp, but the name remains on the hologram and the player remains the region owner

**Comment by Noahkiq** [comment]
^ /shop mod removeowner

**Comment by GriffinCodes** [comment]
Replaced by #599
