### ISSUE TITLE
prevent end portal creation in creative, it plays a sound to everyone on the server

### ISSUE THREAD

**Issue by WakkaFlocka239** [ProjectEdenGG/Issues#575]

**Comment by qixils** [comment]
Opening an end portal does not actually fire an event, making any listener for PortalCreateEvent useless. a simple alternative solution could be cancelling PlayerInteractEvent if the player is holding an eye of ender in the creative world.

**Comment by qixils** [comment]
the sound issue will be mostly fixed on the next restart. (spigot.yml has a config option for setting the sound's radius, though it does not ensure the recipient's world matches the sound's world. this will be PR'd upstream)

**Comment by qixils** [comment]
https://github.com/PaperMC/Paper/pull/6226

**Comment by GriffinCodes** [comment]
~~Portals are no longer created in Creative~~

EDIT: I lied, apparently
