### ISSUE TITLE
players can slingshot themselves into the sky in a minecart using a fishing rod

### ISSUE THREAD

**Issue by WakkaFlocka239** [ProjectEdenGG/Issues#625]
1. Be in survival mode
2. Get in a minecart
3. Look up and use a fishing rod

You still take fall damage when you hit the ground.

Found my NamedAnonymous in OneBlock, works in Survival too, probably works in all worlds

https://i.gyazo.com/7767a99e717321ed1419e8b64545fe2f.gif

**Comment by Pugabyte** [comment]
https://github.com/mcMMO-Dev/mcMMO/commit/b68bbad76642470194ac5708ff105cd422a3d52c

**Comment by lexikiq** [comment]
Fixed by mcMMO-Dev/mcMMO#4508
