### ISSUE TITLE
Setup pet groups

### ISSUE THREAD

**Issue by qixils** [ProjectEdenGG/Issues#647]
The LuckPerms groups for pets from the /store haven't actually been setup yet. Maybe lost in some upgrade. I added the one that someone bought but haven't gotten around to the others. (If anyone beats me to it, make sure to have them inherit the parent pet group for basic pet commands)

**Comment by GriffinCodes** [comment]
![image](https://user-images.githubusercontent.com/12417961/117097368-74d83680-ad39-11eb-8aa3-b57184b07abe.png)
