### ISSUE TITLE
shift double clicking items into your hotbar causes some of the stacks that don't fit, to drop on the ground

### ISSUE THREAD

**Issue by WakkaFlocka239** [ProjectEdenGG/Issues#679]
To reproduce: 
1. Have other items in your hotbar and like 10 stacks of something else in your inventory
2. While in your inventory, pick up a stack of items, hold shift, and double click the same item type in your inventory (not hotbar)

The amount of slots that you have empty will fill with that item type, and some (not all for some reason) of the leftovers, will be tossed onto the ground.

**Comment by WakkaFlocka239** [comment]
Also, in Creative mode, it cancels the action, not allowing you to mass move the items.
Not sure if that's vanilla or not

**Comment by GriffinCodes** [comment]
Why is this labelled eden-api?

**Comment by GriffinCodes** [comment]
Happens when Nexus is not loaded on the server, not caused by us

**Comment by GriffinCodes** [comment]
Caused by StackableItems

**Comment by GriffinCodes** [comment]
Tracking in issue above
