### ISSUE TITLE
Deathmessages command improvements

### ISSUE THREAD

**Issue by phoebumblebee** [ProjectEdenGG/Issues#686]
- [x] Add the command to discord for staff
- [x] Add the ability to include a time duration? E.g. Set someone's death messages to local for 2 hours and it'll be set back to global after that time has passed.

**Comment by GriffinCodes** [comment]
Completed in https://github.com/ProjectEdenGG/Nexus/commit/a9ecc7 and https://github.com/ProjectEdenGG/Nexus/commit/82771d
