### ISSUE TITLE
mcmmo does not block xp gain from Guardian Farms

### ISSUE THREAD

**Issue by milenehan** [ProjectEdenGG/Issues#688]
At my guardian farm I built, using naturally spawned guardians, I can level up mcmmo (sword/axes/archery/unarmed) 
(design: Iskall85 Guardian Farm)

/home powerade98 xp

Wakka told me to write it here!

**Comment by GriffinCodes** [comment]
https://github.com/mcMMO-Dev/mcMMO/issues/4784
