### ISSUE TITLE
1.17

### ISSUE THREAD

**Issue by GriffinCodes** [ProjectEdenGG/Issues#693]
## Blocking
- [x] Spigot
- [x] Paper (https://github.com/PaperMC/Paper/issues/5785)
  - [x] Beta to begin testing
  - [x] Release
- [x] Parchment
  - [x] Use new fork scripts (https://github.com/PaperMC/paperweight-examples)
  - [x] Update API patches
  - [x] Update server patches
- [x] Plugins
  - [x] FAWE ([experimental/incomplete builds](https://ci.athion.net/job/FastAsyncWorldEdit-1.17/), [PR](https://github.com/IntellectualSites/FastAsyncWorldEdit/pull/1120))
  - [x] SimplePets (Update to v6)
  - [x] GlowAPI (https://github.com/InventivetalentDev/GlowAPI/issues/87)
  - [x] [PremiumVanish](https://www.spigotmc.org/resources/premiumvanish-stay-hidden-bungee-support.14404/)
- [x] Nexus
  - [x] Update NMS (all of it will be broken)
- [x] Saturn
- [x] OptiFine

## After
- [x] ~~Version world~~
  - [ ] Separate mcMMO
- [x] ~~Survival world expansion~~
- [x] Resource world
- [ ] Market/VPS updates
- [ ] Plugins
  - [x] BentoBox
  - [ ] Lasso
  - [ ] StopPushing (probably finally dead)
  - [x] Powder (async error)
- [ ] ATP in the end (ensure it supports shulkers?)

**Comment by qixils** [comment]
todo:
- ~~parchment-api: OptionalPlayerLike should extend OptionalLocation~~
- ~~nexus: CraftItemStack#canPlaceOn -> UnsafeValues#canPlaceItemOn~~

**Comment by qixils** [comment]
todo:
- ~~test if #canPlaceItemOn works properly against light blocks (should return false for non-creative players)~~
- ~~fix server patch ordering (item stuff should be last)~~

**Comment by GriffinCodes** [comment]
todo:
- [x] add new mob heads
- [x] add new mobs to ~~killer money~~ and atp
