### ISSUE TITLE
custom image maps aren't loaded in until a player looks at them in hand

### ISSUE THREAD

**Issue by WakkaFlocka239** [ProjectEdenGG/Issues#724]

**Comment by qixils** [comment]
Vanilla bug, should be fixed in 1.17.1

**Comment by GriffinCodes** [comment]
Still occurring on 1.17.1

**Comment by qixils** [comment]
Needs to (also?) be fixed on ImageOnMap's end then: https://github.com/zDevelopers/ImageOnMap/issues/198

**Comment by GriffinCodes** [comment]
Seems that entities are no longer in the chunk immediately after [ChunkLoadEvent](https://github.com/ProjectEdenGG/ImageOnMap/blob/f6eda5892fc337878c546e34244de497fa763df9/src/main/java/fr/moribus/imageonmap/image/MapInitEvent.java#L100-L107). I tried [listening to EntitySpawnEvent](https://i.imgur.com/5okldA6.png) instead but it seems item frames do not throw this event. [Added a periodic task to render all loaded entities](https://github.com/ProjectEdenGG/ImageOnMap/commit/f6eda5892fc337878c546e34244de497fa763df9), but a more elegant solution would be desired (particularly understanding when item frames become available after chunk load)

**Comment by GriffinCodes** [comment]
Fixed by https://github.com/ProjectEdenGG/ImageOnMap/commit/8274f541307ba668ee8ee2336cec84898a552012

**Comment by qixils** [comment]
> Seems that entities are no longer in the chunk immediately after [ChunkLoadEvent](https://github.com/ProjectEdenGG/ImageOnMap/blob/f6eda5892fc337878c546e34244de497fa763df9/src/main/java/fr/moribus/imageonmap/image/MapInitEvent.java#L100-L107)

See https://github.com/PaperMC/Paper/issues/5872
