### ISSUE TITLE
Market rotation

### ISSUE THREAD

**Issue by Drakimau** [ProjectEdenGG/Issues#756]
A chance for people to get cool items that normally wouldn't be found in the admin market for limited time periods.

Suggestions on how it would be implemented:
- separate section of the market 
- could rotate every few days or weeks
- perhaps depending on the rarity/demand of the items said items only stay a certain amount of days
- several different themed lists of items 
- randomly pulled you never know what they could be selling

**Comment by qixils** [comment]
Related: #755

**Comment by GriffinCodes** [comment]
Closing as we dont have /market anymore, 755 would be more likely
