### ISSUE TITLE
Times reset on /mctop

### ISSUE THREAD

**Issue by Drakimau** [ProjectEdenGG/Issues#761]
The rankings on mctop would account for how many times a player has reset said skill. 

Suggestions on how this would be implemented:
- a player who is level 50 but has reset twice would be higher ranked than a level 100 player who has never reset. 
- each reset is equal to the 100 levels, mctop would reflect the sum of resets + current level

**Comment by GriffinCodes** [comment]
https://github.com/ProjectEdenGG/Nexus/commit/d43281927d1d4b699ef2f7296feab452f2ee19fd
