### ISSUE TITLE
Custom recipes 

### ISSUE THREAD

**Issue by Drakimau** [ProjectEdenGG/Issues#763]
Suggested new custom recipes:

- [x] dripstone
- [x] deepslate
- [x] backpacks with 1 shulker box instead of 2 shulker shells + chest
- [x] stairs to planks 
- [x] ~~spore blossom~~

**Comment by Blast-MC** [comment]
backpacks with 1 shulker box instead of 2 shulker shells + chest
> Added shulker box uncrafting (must be empty) because it's the easiest solution right now.

dripstone/deepslate
> uncrafting recipes have been added
