### ISSUE TITLE
Potions for autosort refill

### ISSUE THREAD

**Issue by Drakimau** [ProjectEdenGG/Issues#765]
Similar to blocks and other consumables if you have more than one of the same potion in your inventory drinking one would replace the empty bottle in your inventory with one of the full ones.

**Comment by qixils** [comment]
On one hand, this seems like an obvious bug or missing feature- all items should be replenishable, right? on the other, it would:
1. remove the need for the potion launcher from the mcMMO reset
2. arguably be violating the Minecraft EULA, as it'd be a paid perk which gives a gameplay advantage over other players. i don't believe the auto replenish feature on its own would be considered a gameplay advantage, considering it just saves a few seconds at best from having to grab another stack of blocks, but in a combat scenario i would definitely argue that replenishable potions should be considered a significant gameplay advantage. this would also apply to splash potions, and i'd guess that those currently *do* replenish? if so we may want to look into disabling those, or disabling auto replenish within a few seconds of being damaged by another player
