### ISSUE TITLE
Head dropped announcement 

### ISSUE THREAD

**Issue by Drakimau** [ProjectEdenGG/Issues#770]
If a player kills a mob and said mobs drops a head they would be sent a message so they know to go pick it up. Would be helpful for those who mainly kill things from far away. 

Suggestions on how to implements this:
- A message saying something such as "oh a head!" sent to the player upon drop
- heads being sent to players inboxes instead of dropping as a normal drop

**Comment by GriffinCodes** [comment]
Added message to player
