### ISSUE TITLE
Wither arena still broken, more testing required

### ISSUE THREAD

**Issue by WakkaFlocka239** [ProjectEdenGG/Issues#782]
Puppenjunge started up a wither fight, and their teleport got cancelled
<img src=https://cdn.discordapp.com/attachments/331277920729432065/877827166480519168/Capture.PNG>

**Comment by Blast-MC** [comment]
https://github.com/ProjectEdenGG/Nexus/blob/f87a15b8b94efde48428293db3433c2080d3bd61/src/main/java/gg/projecteden/nexus/features/wither/WitherChallenge.java#L148 Should instead be 
`if (!currentFight.getSpectators().contains(event.getPlayer().getUniqueId()) && (currentFight.alivePlayers == null || !currentFight.getAlivePlayers().contains(event.getPlayer().getUniqueId()))) {`
I will be out of the house until later tonight if someone else could handle this one for me.
