### ISSUE TITLE
Suggestion: Adding a role for tone indicators in the discord

### ISSUE THREAD

**Issue by Lupinez** [ProjectEdenGG/Issues#799]
written conversation can be harder to understand for people who have communication issues or just aren’t used to a certain way someone speaks online, which is why some people use tone indicators. For example if one person and their friend normally joke around in a way that most people would usually interpret as being fighting, putting something like /j (joking), /lh (lighthearted) or /hj (half-joking) can show that they aren't actually being serious.

The role could be assigned using a command and could possibly be added to the semicolon bot. The role would be used to show other people on the discord whether or not the user prefers people to use tone indicators when talking to them.

**Comment by qixils** [comment]
I've been meaning to add configurable role assignments to semicolon, that is being tracked [here](https://gitlab.com/lexikiq/semicolon/-/issues/135). In the mean time I can add some hardcoded commands, though admittedly I (unfortunately) don't believe that users would regularly check/use a tone-indicator role.

**Comment by WakkaFlocka239** [comment]
I don't see this being very helpful as discord roles & we need as many available roles as we can get
