### ISSUE TITLE
Player names aren't rendering in death messages

### ISSUE THREAD

**Issue by qixils** [ProjectEdenGG/Issues#814]
Names are no longer rendering in death messages. did a plugin update recently to break this?

![image](https://user-images.githubusercontent.com/13265322/134787324-a0ea3529-63c2-4ef6-87d1-d5e77724714c.png)

**Comment by GriffinCodes** [comment]
~~Delete the team `wither-<first 8 of uuid>`~~

Issue more widespread, might be related to teams still though

**Comment by GriffinCodes** [comment]
In `DeathMessagesCommand#handleArgument`: 
```
		for (Component child : component.children())
			if (child instanceof TextComponent childText)
				Nexus.debug("child: " + childText.content());
```
![image](https://user-images.githubusercontent.com/12417961/135328953-9bac46e1-cb50-4bdc-a56b-9077072e9a96.png)
