### ISSUE TITLE
higher than vanilla enchanting bug

### ISSUE THREAD

**Issue by WakkaFlocka239** [ProjectEdenGG/Issues#826]
The result item should have sharpness 6 on it, not 5.
Item 1
<img src=https://i.imgur.com/rwHchtf.png>
Item 2
<img src=https://i.imgur.com/SC3vnpH.png>

Result
<img src=https://i.imgur.com/Ls5JMlk.png>

**Comment by GriffinCodes** [comment]
This is an enhancement, not a bug

**Comment by GriffinCodes** [comment]
Related: #819
