### ISSUE TITLE
Kawaiis Creative ticket

### ISSUE THREAD

**Issue by FilidDamhsoir** [ProjectEdenGG/Issues#830]
https://discord.com/channels/132680070480396288/331842528854802443/912506685262811176

This is a creative plot.    For some reason blocks cannot be placed above the current level of the ground in any spot- you can break down and then place blocks, but its like there's an invisible barrier that prevents block placement, but not movement above any of the existing blocks.  I tried setting myself to owner, that didn't change the behavior.

I'm on the vanilla launcher as is Kawaii,  Midnight is on fabric. None of us can place.

I used world edit to copy the existing build, moved it to a plot that was working fine.  Once the past finished, the new plot had the same issue.  I then cleared the second plot, and it resumed working correctly. 
 I suspect FAWE or something this dofus did when world editing the inital build, but I cannot figure out what. I had console open and did not see any errors, nor was there anything in game.  It just reacted like we were all in vanish if we tried to place blocks, unless we dug down into the ground first. So like on the mountain they had built with WE, you have to break part of the mountain, can't add above it.  Down in the cave they built you can't place inside the cave, only break the floor and begin placing.   its like all the air blocks are broken. 

For now the ticket is in place so you can teleport to the affected plot.  I have set myself to owner, and set Kawaii up with a new, empty plot to work on.

**Comment by qixils** [comment]
> They replaced all air with light blocks, and we made it so when you place a block into a light block, it gets cancelled, so you could only edit where existing blocks were, because there wasn't a light block there.

Fixed by https://github.com/ProjectEdenGG/Nexus/commit/153c8244982385b8678cfa0776766b07e51e808e
