### ISSUE TITLE
Minigame collectable pirate hats need to be updated

### ISSUE THREAD

**Issue by WakkaFlocka239** [ProjectEdenGG/Issues#847]
<img src=https://i.imgur.com/SXJkDo0.png>

New definitions are:
- Material = Leather Horse Armor
- Model Data:
  - Cavalier: 4000
  - Bicorn: 4001
  - Bicorn Side: 4002
  - Tricorn: 4003

Other notes:
- Leather pirate hats are the same, and not dyeable
- Will need to support dyeable, otherwise the default color will be brown
             <img src=https://i.imgur.com/yD0C63r.png>

**Comment by qixils** [comment]
fixed by https://github.com/ProjectEdenGG/Nexus/commit/1c8cc7200a523a87ac36abd544582f57b94fe8e1
