### ISSUE TITLE
Interaction with costume in off hand cancels event

### ISSUE THREAD

**Issue by Cynshiii** [ProjectEdenGG/Issues#868]
When attempting to enter a boat with a costume in your off hand (such as the rainbow bracelet) while in creative mode, you cannot enter the boat. It works fine in survival, and if there's a vanilla item in off hand (even something like armor that you would put on) it will let you in the boat. But if you have a costume in your off hand and are in creative mode, boat no work.

**Comment by WakkaFlocka239** [comment]
Cannot reproduce this anymore, potentially was fixed since reporting.
