### ISSUE TITLE
Turf Wars async pasting improperly

### ISSUE THREAD

**Issue by WakkaFlocka239** [ProjectEdenGG/Issues#880]
https://user-images.githubusercontent.com/9204295/228091731-0ff481ca-fbb9-4e03-b286-1d37b0ff824a.mp4

I think somehow [8a3de57](https://github.com/ProjectEdenGG/Nexus/commit/8a3de57abb5de86454ef324ce08dad48e50d60d4) broke Turf Wars

**Comment by GriffinCodes** [comment]
https://github.com/ProjectEdenGG/Nexus/commit/4930635e8ca84ad30119bec29322eb1536776041

**Comment by WakkaFlocka239** [comment]
This is still occurring

**Comment by GriffinCodes** [comment]
Cannot reproduce
