### ISSUE TITLE
Add new costumes

### ISSUE THREAD

**Issue by WakkaFlocka239** [ProjectEdenGG/Issues#882]
TV Head
Flower Crown	
	
	Paper:
		{"predicate": {"custom_model_data": 22322}, "model": "projecteden/costumes/hat/misc/tv_head"},
		{"predicate": {"custom_model_data": 22323}, "model": "projecteden/costumes/hat/misc/flower_crown"},

**Comment by GriffinCodes** [comment]
This process is automated
