### ISSUE TITLE
Turf Wars bugs

### ISSUE THREAD

**Issue by WakkaFlocka239** [ProjectEdenGG/Issues#889]
errors on join
![image](https://user-images.githubusercontent.com/9204295/230744476-d05a4ee2-0705-47fc-89aa-b657f2a39c7c.png)

repetitive errors
![image](https://user-images.githubusercontent.com/9204295/230744485-03bee58c-e733-48a2-ac53-d5bba5784fc6.png)

Probably related, but a player wasn't teleported from the lobby into the map, although they hit the teleport button right as everyone was teleported into the map, so maybe that was the cause?

Both maps have been disabled

**Comment by Blast-MC** [comment]
first issue fixed with https://github.com/ProjectEdenGG/Nexus/commit/aa4641e938a1f324464ae2eda102d923c29d97b6
CNR the second issue (it was a missing region, may have been fixed)
