### ISSUE TITLE
ChatGames issues

### ISSUE THREAD

**Issue by WakkaFlocka239** [ProjectEdenGG/Issues#891]
Shouldn't there be missing letters?
<img src=https://i.imgur.com/NHd6sTG.png>

also could also use the similarity checker library that pixeldrop uses to get a better scrambled word
`[ChatGames] Unscramble the phrase: bee nswap egg. Type the full phrase in chat!`

Disabled features are also in the game-
`[ChatGames] Game over! The correct answer was brush.`
<img src=https://i.imgur.com/QDuFDHv.png>

**Comment by Blast-MC** [comment]
fixed with https://github.com/ProjectEdenGG/Nexus/commit/97f4a8ada132176c92ab56b075977b2d721f7ea3
