### ISSUE TITLE
1.20 bug fix, possibly redesign mage guild enchanting table at spawn

### ISSUE THREAD

**Issue by WakkaFlocka239** [ProjectEdenGG/Issues#893]
At Survival spawn, there's an enchanting table at the top of the mage guild tower, with light blocks in between the bookshelves and enchanting table purposefully blocking the bonuses to the enchanting table.

The 1.20 update contains a bug fix that may fix this, and thus we may need to redesign that room if so.

Bugfix: https://bugs.mojang.com/browse/MC-2474

**Comment by Blast-MC** [comment]
new build does not have the enchant table. replaced the current bookshelves with chiseled bookshelves
