### ISSUE TITLE
Can't Vanish

### ISSUE THREAD

**Issue by KnackWhack** [ProjectEdenGG/Issues#898]
As a Mod, can't do the command and doesn't tab complete.

**Comment by WakkaFlocka239** [comment]
VanishCommand permission was changed from `Group.MODERATOR` to `Ladder.ARCHITECT`
however moderators do not have permission to `Ladder.ARCHITECT`

**Comment by WakkaFlocka239** [comment]
Changed the permission to `nexus.vanish` and added it to both moderators & architects.
